# Generated by Django 5.2.11 on 2026-03-13 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('locale', models.CharField(blank=True, default='uz', max_length=16)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='users_userd_user_id_e90fd8_idx'), models.Index(fields=['device_id'], name='users_userd_device__c17433_idx'), models.Index(fields=['fcm_token'], name='users_userd_fcm_tok_380865_idx')],
            },
        ),
    ]
