# Generated by Django 5.2.11 on 2026-04-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_deleted_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otp',
            name='users_otp_phone_c8c281_idx',
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('delete', 'Delete')], default='login', max_length=10),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone', 'purpose', 'is_used', 'expires_at'], name='users_otp_phone_e2a54e_idx'),
        ),
    ]
