# Generated by Django 6.0.1 on 2026-02-03 18:30

from django.db import migrations, models
from django.db.models import F


def copy_name_to_translations(apps, schema_editor):
    Category = apps.get_model("finance", "Category")
    Category.objects.filter(name_uz="").update(
        name_uz=F("name"),
        name_ru=F("name"),
        name_en=F("name"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_transaction_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_uz",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.RunPython(copy_name_to_translations, migrations.RunPython.noop),
    ]
