# Generated by Django 5.2.11 on 2026-04-19 08:48

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_category_name_en_alter_category_name_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualcard",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
        ),
    ]
